services:
  phpipam-web:
    image: phpipam/phpipam-www:1.6x
    ports:
      - "${IPAM_HTTP_PORT}:80"
    restart: "${RESTART_POLICY}"
    env_file:
     - ${ENV_DIRECTORY}/.env_web
    volumes:
      - ${DATA_DIRECTORY}/web/phpipam/css/images/logo:/phpipam/css/images/logo
      - ${DATA_DIRECTORY}/web/usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:1.6x
    restart: "${RESTART_POLICY}"
    env_file:
     - ${ENV_DIRECTORY}/.env_cron
    volumes:
      - ${DATA_DIRECTORY}/cron/usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb

  phpipam-mariadb:
    image: mariadb:latest
    restart: "${RESTART_POLICY}"
    env_file:
     - ${ENV_DIRECTORY}/.env_mariadb
    volumes:
      - ${DATA_DIRECTORY}/mariadb/var/lib/mysql:/var/lib/mysql
